(()=>{'use strict';
function pieceSvg(key){const type=key[1],label=TYPES[type]?.name||'chess piece';return `<span class="piece-icon piece-mask-${key}" role="img" aria-label="${label}"></span>`}
const POINT_CAP=12;const TYPES={q:{name:'Queen',value:10},r:{name:'Rook',value:5},b:{name:'Bishop',value:3},n:{name:'Knight',value:3},p:{name:'Pawn',value:1}};const FILES='abcd';
let board,turn,points,phase,selected,legal,lastMove,actions,history,over,endReason=null,resignedSide=null,pending,purchase,setupSide,reviewResults=null,reviewView=null,engineHint=null,reviewBusy=false,reviewToken=0,engineToken=0,gameMode='twoPlayer',engineAutoPending=false;
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x)),inside=(r,c)=>r>=0&&r<4&&c>=0&&c<4,sideOf=p=>p&&p[0],nameSq=(r,c)=>FILES[c]+(4-r);
function freshBoard(){return Array.from({length:4},()=>Array(4).fill(null))}
function reset(){board=freshBoard();turn='w';points={w:5,b:5};phase='setup';selected=null;legal=[];lastMove=null;actions=[];history=[];over=false;endReason=null;resignedSide=null;pending=null;purchase=null;setupSide='w';reviewResults=null;reviewView=null;engineHint=null;reviewBusy=false;engineAutoPending=false;reviewToken++;engineToken++;$('enginePanel').classList.remove('open');$('reviewPanel').classList.remove('open');render()}
function save(){history.push({board:copy(board),turn,points:{...points},phase,lastMove:lastMove&&copy(lastMove),actions:copy(actions),over,endReason,resignedSide,purchase,setupSide})}
function undo(){if(!history.length)return;const undoPair=gameMode==='engine'&&turn==='w'&&actions.length&&actions[actions.length-1].side==='b'&&history.length>1;let restored;for(let i=0;i<(undoPair?2:1);i++)restored=copy(history.pop());({board,turn,points,phase,lastMove,actions,over,endReason,resignedSide,purchase,setupSide}=restored);selected=null;legal=[];pending=null;reviewResults=null;reviewView=null;engineHint=null;reviewBusy=false;engineAutoPending=false;reviewToken++;engineToken++;$('enginePanel').classList.remove('open');$('reviewPanel').classList.remove('open');$('promotionModal').classList.remove('open');render()}
function kingAt(b,s){for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(b[r][c]===s+'k')return[r,c];return null}
function attacked(b,r,c,by){for(let rr=0;rr<4;rr++)for(let cc=0;cc<4;cc++){const p=b[rr][cc];if(sideOf(p)!==by)continue;const dr=r-rr,dc=c-cc,k=p[1];if(k==='p'){if(dr===(by==='w'?-1:1)&&Math.abs(dc)===1)return true}else if(k==='n'){if(Math.abs(dr)*Math.abs(dc)===2)return true}else if(k==='k'){if(Math.max(Math.abs(dr),Math.abs(dc))===1)return true}else{const diagonal=Math.abs(dr)===Math.abs(dc)&&dr!==0,straight=(dr===0)!==(dc===0);if((k==='b'&&!diagonal)||(k==='r'&&!straight)||(k==='q'&&!diagonal&&!straight))continue;const sr=Math.sign(dr),sc=Math.sign(dc);let tr=rr+sr,tc=cc+sc,clear=true;while(tr!==r||tc!==c){if(b[tr][tc]){clear=false;break}tr+=sr;tc+=sc}if(clear)return true}}return false}
function inCheck(b,s){const k=kingAt(b,s);return k?attacked(b,k[0],k[1],s==='w'?'b':'w'):false}
function pseudo(b,r,c){const p=b[r][c];if(!p)return[];const s=sideOf(p),k=p[1],out=[];const add=(rr,cc,extra={})=>{if(inside(rr,cc)&&sideOf(b[rr][cc])!==s&&b[rr][cc]!==((s==='w'?'b':'w')+'k'))out.push({from:[r,c],to:[rr,cc],piece:p,capture:b[rr][cc],...extra})};
if(k==='p'){const d=s==='w'?-1:1,last=s==='w'?0:3,rr=r+d;if(inside(rr,c)&&!b[rr][c])add(rr,c,{promotion:rr===last});for(const dc of [-1,1])if(inside(rr,c+dc)&&sideOf(b[rr][c+dc])&&sideOf(b[rr][c+dc])!==s)add(rr,c+dc,{promotion:rr===last})}
if(k==='n')for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);
if(['b','r','q'].includes(k)){const dirs=[];if(k!=='r')dirs.push([-1,-1],[-1,1],[1,-1],[1,1]);if(k!=='b')dirs.push([-1,0],[1,0],[0,-1],[0,1]);for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){if(!b[rr][cc])out.push({from:[r,c],to:[rr,cc],piece:p,capture:null});else{if(sideOf(b[rr][cc])!==s)out.push({from:[r,c],to:[rr,cc],piece:p,capture:b[rr][cc]});break}rr+=dr;cc+=dc}}}
if(k==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc)}return out}
function apply(b,m,promo){const[r,c]=m.from,[rr,cc]=m.to;b[r][c]=null;b[rr][cc]=promo?sideOf(m.piece)+promo:m.piece}
function legalMovesFor(b,s){const out=[];if(!kingAt(b,s))return out;const check=inCheck(b,s);for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(sideOf(b[r][c])===s){const p=b[r][c];if(p[1]==='k'&&!check)continue;for(const m of pseudo(b,r,c)){const next=copy(b);apply(next,m,m.promotion?'q':null);if(!inCheck(next,s))out.push(m)}}return out}
function allLegal(s=turn){return legalMovesFor(board,s)}
function sanFor(b,s,m,promo=null){const[fromRow,fromCol]=m.from,[toRow,toCol]=m.to,piece=m.piece[1],capture=!!m.capture,letters={k:'K',q:'Q',r:'R',b:'B',n:'N'};let text=piece==='p'?(capture?FILES[fromCol]:''):(letters[piece]||'');if(piece!=='p'){const rivals=legalMovesFor(b,s).filter(other=>other.piece[1]===piece&&other.to[0]===toRow&&other.to[1]===toCol&&(other.from[0]!==fromRow||other.from[1]!==fromCol));if(rivals.length){const sameFile=rivals.some(other=>other.from[1]===fromCol),sameRank=rivals.some(other=>other.from[0]===fromRow);text+=!sameFile?FILES[fromCol]:!sameRank?String(4-fromRow):FILES[fromCol]+String(4-fromRow)}}text+=(capture?'x':'')+nameSq(toRow,toCol);if(promo)text+='='+((letters[promo]||'Q'));return text}
function san(m,promo){return sanFor(board,turn,m,promo)}
function homeRow(s){return s==='w'?3:0}function ownHalf(s,r){return s==='w'?r>=2:r<=1}
function ownedCount(s,type,b=board){let n=0;for(const row of b)for(const p of row)if(p===s+type)n++;return n}
function canBuyType(s,type,b=board){const cap={q:1,r:2,b:2,n:2,p:3}[type];return ownedCount(s,type,b)<cap}
function safeDropFor(s,type,r,c,b,bank){if(!inside(r,c)||b[r][c]||!ownHalf(s,r)||bank[s]<TYPES[type].value||!canBuyType(s,type,b))return false;if(type==='p'){for(let rr=0;rr<4;rr++)if(b[rr][c]===s+'p')return false}const next=copy(b);next[r][c]=s+type;return !inCheck(next,s)}
function safeDrop(s,type,r,c){return safeDropFor(s,type,r,c,board,points)}
function hasPurchaseSpot(s,type){if(!canBuyType(s,type)||points[s]<TYPES[type].value)return false;for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(safeDrop(s,type,r,c))return true;return false}
function canBuyToEscapeFor(s,b,bank){for(const type of Object.keys(TYPES))for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(safeDropFor(s,type,r,c,b,bank))return true;return false}
function canBuyToEscape(s){return canBuyToEscapeFor(s,board,points)}
function isMate(){return inCheck(board,turn)&&allLegal(turn).length===0&&!canBuyToEscape(turn)}
function positionSnapshot(){return{board:copy(board),turn,points:{...points},lastMove:lastMove&&copy(lastMove)}}
function logAction(s,text,delta,before,detail){actions.push({side:s,text,delta,before,after:positionSnapshot(),detail})}
function resign(){if(phase!=="play"||over)return;save();resignedSide=gameMode==="engine"?"w":turn;endReason="resign";over=true;pending=null;purchase=null;selected=null;legal=[];engineAutoPending=false;engineToken++;reviewView=null;engineHint=null;document.getElementById("promotionModal").classList.remove("open");document.getElementById("enginePanel").classList.remove("open");render()}function passTurn(){turn=turn==='w'?'b':'w';selected=null;legal=[];purchase=null;engineHint=null;reviewView=null;engineToken++;$('enginePanel').classList.remove('open');$('reviewPanel').classList.remove('open');const mate=isMate();if(mate)over=true}
const ENGINE_DEPTH=6,ENGINE_TIME_MS=1250,REVIEW_TIME_MS=220,MATE_SCORE=1000,INF=10000,ENGINE_VALUES={p:1,n:3,b:3,r:5,q:10};
function engineActions(s){if(s.over)return[];const out=[],check=inCheck(s.board,s.turn);for(const m of legalMovesFor(s.board,s.turn)){if(m.promotion){for(const promo of ['q','r','b','n'])if(promo!=='q'||ownedCount(s.turn,'q',s.board)<1)out.push({type:'move',move:copy(m),promo});}else out.push({type:'move',move:copy(m),promo:null})}for(const type of Object.keys(TYPES))for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(safeDropFor(s.turn,type,r,c,s.board,s.points))out.push({type:'buy',piece:type,to:[r,c]});if(!check)out.push({type:'skip'});return out}
function engineNext(s,a){const n={board:copy(s.board),turn:s.turn,points:{...s.points},lastMove:s.lastMove&&copy(s.lastMove),over:false};if(a.type==='skip')n.points[n.turn]=Math.min(POINT_CAP,n.points[n.turn]+2);else if(a.type==='buy'){n.board[a.to[0]][a.to[1]]=n.turn+a.piece;n.points[n.turn]-=TYPES[a.piece].value}else{apply(n.board,a.move,a.promo);n.lastMove={from:a.move.from,to:a.move.to}}n.turn=n.turn==='w'?'b':'w';return n}
function stateMate(s){return inCheck(s.board,s.turn)&&engineActions(s).length===0}
function evaluate(s){let score=s.points.w-s.points.b;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const p=s.board[r][c];if(!p||p[1]==='k')continue;const sign=p[0]==='w'?1:-1,v=ENGINE_VALUES[p[1]]||0,center=(1.5-Math.abs(1.5-r))+(1.5-Math.abs(1.5-c));score+=sign*(v+center*.035);const enemy=p[0]==='w'?'b':'w';if(attacked(s.board,r,c,enemy)){const defended=attacked(s.board,r,c,p[0]);score-=sign*v*(defended?.12:.38)}}if(inCheck(s.board,'w'))score-=.65;if(inCheck(s.board,'b'))score+=.65;return score}
function orderEngineActions(s,choices){return choices.map((a,i)=>{let score=0;if(a.type==='move'){const victim=a.move.capture,attacker=a.move.piece;score+=(victim?(ENGINE_VALUES[victim[1]]||0)*10-(ENGINE_VALUES[attacker[1]]||0):0)+(a.promo?(ENGINE_VALUES[a.promo]-1)*9:0);const next=engineNext(s,a);if(inCheck(next.board,next.turn))score+=7}else if(a.type==='buy')score+=2*(ENGINE_VALUES[a.piece]||0);else score+=1;return{a,i,score}}).sort((x,y)=>y.score-x.score||x.i-y.i).map(x=>x.a)}
function searchValue(s,depth,alpha,beta,ply,ctx){if((++ctx.nodes&63)===0&&ctx.clock()>=ctx.deadline)throw ctx.timeout;if(s.over)return s.turn==='w'?-MATE_SCORE+ply:MATE_SCORE-ply;const check=inCheck(s.board,s.turn);if(depth<=0&&!check)return evaluate(s);const choices=engineActions(s);if(check&&!choices.length)return s.turn==='w'?-MATE_SCORE+ply:MATE_SCORE-ply;if(depth<=0||!choices.length)return evaluate(s);const maximizing=s.turn==='w';let best=maximizing?-INF:INF;for(const a of orderEngineActions(s,choices)){const value=searchValue(engineNext(s,a),depth-1,alpha,beta,ply+1,ctx);if(maximizing){best=Math.max(best,value);alpha=Math.max(alpha,best)}else{best=Math.min(best,value);beta=Math.min(beta,best)}if(beta<=alpha)break}return best}
function sameEngineAction(a,d){if(!a||!d||a.type!==d.type)return false;if(a.type==='skip')return true;if(a.type==='buy')return a.piece===d.piece&&a.to[0]===d.to[0]&&a.to[1]===d.to[1];return a.promo===(d.promo||null)&&a.move.from[0]===d.move.from[0]&&a.move.from[1]===d.move.from[1]&&a.move.to[0]===d.move.to[0]&&a.move.to[1]===d.move.to[1]}
function analyzePosition(raw,played=null,maxDepth=ENGINE_DEPTH,budget=ENGINE_TIME_MS){const clock=()=>globalThis.performance?.now?.()??Date.now(),started=clock(),ctx={nodes:0,deadline:started+budget,clock,timeout:{}},s={board:copy(raw.board),turn:raw.turn,points:{...raw.points},lastMove:raw.lastMove&&copy(raw.lastMove),over:false},choices=orderEngineActions(s,engineActions(s));let best=null,bestScore=s.turn==='w'?-INF:INF,playedScore=null,completedDepth=0;if(!choices.length)return{state:s,best,bestScore,playedScore,depth:0,nodes:ctx.nodes,elapsed:clock()-started};for(let depth=1;depth<=maxDepth;depth++){let iterBest=null,iterBestScore=s.turn==='w'?-INF:INF,iterPlayedScore=null,alpha=-INF,beta=INF;try{for(const a of choices){const isPlayed=sameEngineAction(a,played),value=searchValue(engineNext(s,a),depth-1,isPlayed?-INF:alpha,isPlayed?INF:beta,1,ctx);if(isPlayed)iterPlayedScore=value;if((s.turn==='w'&&value>iterBestScore)||(s.turn==='b'&&value<iterBestScore)){iterBest=a;iterBestScore=value}if(s.turn==='w')alpha=Math.max(alpha,iterBestScore);else beta=Math.min(beta,iterBestScore)}best=iterBest;bestScore=iterBestScore;playedScore=iterPlayedScore;completedDepth=depth}catch(e){if(e!==ctx.timeout)throw e;break}if(clock()>=ctx.deadline)break}return{state:s,best,bestScore,playedScore,depth:completedDepth,nodes:ctx.nodes,elapsed:clock()-started}}function formatEngineAction(s,a){if(!a)return'No legal action';if(a.type==='skip')return'// · skip and earn 2 points';if(a.type==='buy'){const next=engineNext(s,a),suffix=inCheck(next.board,next.turn)?(stateMate(next)?'#':'+'):'';return`${({q:'Q',r:'R',b:'B',n:'N',p:'P'})[a.piece]}/${nameSq(...a.to)}${suffix} · buy ${TYPES[a.piece].name}`}let text=sanFor(s.board,s.turn,a.move,a.promo),next=engineNext(s,a);if(inCheck(next.board,next.turn))text+=stateMate(next)?'#':'+';return text}
function formatScore(score){if(Math.abs(score)>MATE_SCORE-12){const moves=Math.max(1,Math.ceil((MATE_SCORE-Math.abs(score))/2));return`Mate in ${moves} for ${score>0?'White':'Black'}`}return`${score>0?'+':''}${score.toFixed(1)} for White`}
function gradeLoss(loss){if(loss<=.45)return'Excellent';if(loss<=1.1)return'Good';if(loss<=2.4)return'Inaccuracy';if(loss<=4.5)return'Mistake';return'Blunder'}
function gradeScore(grade){return({Blunder:0,Mistake:1,Inaccuracy:2,Good:3,Excellent:4,Best:5,Brilliant:5})[grade]||0}function gradeSymbol(grade){return({Brilliant:'!!',Best:'★',Excellent:'!',Good:'✓',Inaccuracy:'?!',Mistake:'?',Blunder:'??'})[grade]||'·'}
function reviewLossLabel(best,played,loss){const mateMoves=value=>Math.max(1,Math.ceil((MATE_SCORE-Math.abs(value))/2));if(played<-(MATE_SCORE-12))return`Mate in ${mateMoves(played)}`;if(best>MATE_SCORE-12&&loss>.12)return`Missed mate in ${mateMoves(best)}`;return`${loss.toFixed(1)} pts`}
function toggleGameMode(){gameMode=gameMode==='engine'?'twoPlayer':'engine';engineAutoPending=false;engineToken++;selected=null;legal=[];purchase=null;engineHint=null;$('enginePanel').classList.remove('open');render();scheduleEngineTurn()}
function scheduleEngineTurn(){if(gameMode!=='engine'||phase!=='play'||turn!=='b'||over||engineAutoPending)return;engineAutoPending=true;const token=++engineToken;render();setTimeout(()=>{if(token!==engineToken)return;if(gameMode!=='engine'||phase!=='play'||turn!=='b'||over){engineAutoPending=false;render();return}try{const result=analyzePosition(positionSnapshot()),action=result.best;engineAutoPending=false;if(!action){render();toast('The engine found no legal action');return}if(action.type==='skip')doSkip();else if(action.type==='buy'){purchase=action.piece;doBuy(action.piece,...action.to)}else doMove(action.move,action.promo)}catch(error){engineAutoPending=false;render();toast('Engine move failed');console.error(error)}},80)}function runEngine(){if(phase!=='play'||over||reviewBusy)return;const button=$('engineButton'),panel=$('enginePanel'),token=++engineToken,state=positionSnapshot();button.disabled=true;panel.classList.add('open');$('engineText').textContent='Thinking…';$('engineScore').textContent=`Searching up to ${ENGINE_DEPTH} plies · ≤1.25s`;setTimeout(()=>{if(token!==engineToken)return;const result=analyzePosition(state);engineHint=result.best;reviewView=null;render();panel.classList.add('open');$('engineText').textContent=result.best?`Best action: ${formatEngineAction(result.state,result.best)}`:'No legal action found.';$('engineScore').textContent=`Evaluation: ${formatScore(result.bestScore)} · ${result.depth}-ply search · ${(result.elapsed/1000).toFixed(2)}s`;button.disabled=false},30)}
function renderReviewRows(){const list=$('reviewList');list.innerHTML='';if(!reviewResults?.length){list.innerHTML='<div class="empty">No moves to review.</div>';return}reviewResults.forEach(r=>{const row=document.createElement('div');row.className='review-row'+(reviewView===r?' active':'');row.innerHTML=`<span class="review-icon rating-${r.grade.toLowerCase()}" title="${r.grade}" aria-label="${r.grade}">${gradeSymbol(r.grade)}</span><span class="review-move"><b>${r.side==='w'?'W':'B'}</b> &nbsp;${esc(r.played)}</span><span class="review-grade rating-text-${r.grade.toLowerCase()}">${r.grade} · ${r.lossLabel}</span><span class="review-best">Best: ${esc(r.bestText)}</span>`;row.onclick=()=>{reviewView=r;engineHint=null;render()};list.appendChild(row)})}
const BRILLIANT_NEAR_BEST=.5,BRILLIANT_WINNING_BEFORE=5,BRILLIANT_MIN_ADVANTAGE=1;function isSacrificeOffer(entry){const d=entry.detail;if(d.type!=='move'||!entry.after)return false;const[r,c]=d.move.to,p=entry.after.board[r][c],enemy=entry.side==='w'?'b':'w',movedValue=ENGINE_VALUES[d.move.piece?.[1]]||0,capturedValue=ENGINE_VALUES[d.move.capture?.[1]]||0;if(sideOf(p)!==entry.side||movedValue<=capturedValue)return false;return legalMovesFor(entry.after.board,enemy).some(m=>m.to[0]===r&&m.to[1]===c&&m.capture===p)}function isBrilliantAction(entry,analysis,sideEval){if(!isSacrificeOffer(entry)||analysis.playedScore===null||!analysis.best)return false;const sign=entry.side==='w'?1:-1,best=analysis.bestScore*sign,nearBest=best-sideEval<=BRILLIANT_NEAR_BEST,notAlreadyWinning=best<BRILLIANT_WINNING_BEFORE,goodResult=sideEval>=BRILLIANT_MIN_ADVANTAGE||sideEval>=MATE_SCORE-12;return nearBest&&notAlreadyWinning&&goodResult}function reviewMarkSquare(result){const d=result.detail;if(d.type==='move')return d.move.to;if(d.type==='skip')return kingAt(result.position.board,result.side);return d.type==='buy'?d.to:null}
function startReview(){const reviewActions=actions.filter(a=>a.detail?.type!=='setup');if(!over||reviewBusy||!reviewActions.length)return;const token=++reviewToken;reviewBusy=true;reviewResults=[];reviewView=null;engineHint=null;$('enginePanel').classList.remove('open');$('reviewPanel').classList.add('open');$('reviewSummary').textContent='Reviewing each action with the Chass engine…';$('reviewProgress').textContent=`0 / ${reviewActions.length} actions`;$('reviewList').innerHTML='';const total=reviewActions.length;let i=0;const step=()=>{if(token!==reviewToken)return;if(i>=total){reviewBusy=false;const accuracyFor=side=>{const rows=reviewResults.filter(r=>r.side===side);if(!rows.length)return'— (no rated actions)';const earned=rows.reduce((n,r)=>n+gradeScore(r.grade),0),maximum=rows.length*5;return`${Math.round(100*earned/maximum)}% (${earned}/${maximum} rating points)`};$('reviewSummary').textContent=`Estimated accuracy · White ${accuracyFor('w')} · Black ${accuracyFor('b')} (0–5 points per action).`;$('reviewProgress').textContent=`${reviewResults.length} actions reviewed · select an entry to see the best move on the board.`;renderReviewRows();return}const entry=reviewActions[i],analysis=analyzePosition(entry.before,entry.detail,ENGINE_DEPTH,REVIEW_TIME_MS),sideScore=x=>entry.side==='w'?x:-x,best=sideScore(analysis.bestScore),played=sideScore(analysis.playedScore??analysis.bestScore),loss=Math.max(0,best-played);reviewResults.push({side:entry.side,played:entry.text,detail:entry.detail,bestText:formatEngineAction(analysis.state,analysis.best),best:analysis.best,position:entry.after||entry.before,loss,grade:isBrilliantAction(entry,analysis,played)?'Brilliant':best>MATE_SCORE-12&&played<best-.12?(loss>4.5?'Blunder':'Mistake'):sameEngineAction(analysis.best,entry.detail)?'Best':gradeLoss(loss),score:best,lossLabel:reviewLossLabel(best,played,loss)});i++;$('reviewProgress').textContent=`${i} / ${total} actions`;renderReviewRows();setTimeout(step,15)};setTimeout(step,20)}function doSkip(){if(phase!=='play'||over||inCheck(board,turn))return;save();const who=turn,before=positionSnapshot(),earned=Math.min(2,POINT_CAP-points[who]);points[who]+=earned;passTurn();logAction(who,'//',earned,before,{type:'skip'});render();scheduleEngineTurn()}
function doBuy(type,r,c){if(phase!=='play'||over||!purchase||!safeDrop(turn,type,r,c))return;save();const who=turn,before=positionSnapshot(),cost=TYPES[type].value;board[r][c]=who+type;points[who]-=cost;passTurn();const suffix=inCheck(board,turn)?(over?'#':'+'):'';logAction(who,`${({q:'Q',r:'R',b:'B',n:'N',p:'P'})[type]}/${nameSq(r,c)}${suffix}`,-cost,before,{type:'buy',piece:type,to:[r,c]});render();scheduleEngineTurn()}
function doMove(m,promo){if(phase!=='play'||over)return;save();const who=turn,before=positionSnapshot(),notation=san(m,promo);apply(board,m,promo);lastMove={from:m.from,to:m.to};passTurn();const suffix=inCheck(board,turn)?(over?'#':'+'):'';logAction(who,notation+suffix,0,before,{type:'move',move:copy(m),promo:promo||null});render();scheduleEngineTurn()}
function engineKingColumn(){let chosen=null,lowest=INF;for(let c=0;c<4;c++){if(board[homeRow('b')][c])continue;const candidate=copy(board);candidate[homeRow('b')][c]='bk';const result=analyzePosition({board:candidate,turn:'w',points:{...points},lastMove:null},null,2,180);if(result.best&&(result.bestScore<lowest-1e-6||(Math.abs(result.bestScore-lowest)<=1e-6&&(chosen===null||Math.abs(c-1.5)<Math.abs(chosen-1.5))))){lowest=result.bestScore;chosen=c}}return chosen??[0,1,2,3].find(c=>!board[0][c])}function placeKing(r,c){if(phase!=='setup'||r!==homeRow(setupSide)||board[r][c])return;save();const side=setupSide,before=positionSnapshot();board[r][c]=side+'k';logAction(side,'k'+nameSq(r,c),0,before,{type:'setup',piece:'k',to:[r,c]});if(side==='w'){if(gameMode==='engine'){const blackColumn=engineKingColumn();if(blackColumn!==undefined){const blackBefore=positionSnapshot();board[0][blackColumn]='bk';logAction('b','k'+nameSq(0,blackColumn),0,blackBefore,{type:'setup',piece:'k',to:[0,blackColumn]})}phase='play';turn='w';setupSide=null}else setupSide='b'}else{phase='play';turn='w';setupSide=null}render()}
function clickSquare(r,c){if(over||pending||engineAutoPending||(gameMode==='engine'&&turn==='b'))return;if(phase==='setup'){placeKing(r,c);return}const p=board[r][c];if(p&&sideOf(p)===turn){purchase=null;selected=null;legal=[];if(p[1]!=='k'||inCheck(board,turn)){selected=[r,c];legal=allLegal().filter(x=>x.from[0]===r&&x.from[1]===c)}else toast('King may move only while in check');render();return}if(purchase){if(safeDrop(turn,purchase,r,c)){doBuy(purchase,r,c)}else toast('Choose an empty square in your half');return}if(selected){const m=legal.find(x=>x.to[0]===r&&x.to[1]===c);if(m){if(m.promotion){showPromotion(m);return}doMove(m);return}selected=null;legal=[];render()}}
function showPromotion(m){pending=m;$('promotionChoices').innerHTML='';for(const k of ['q','r','b','n']){if(k==='q'&&ownedCount(turn,'q')>=1)continue;const btn=document.createElement('button');btn.innerHTML=pieceSvg(turn+k);btn.className=turn==='w'?'white-piece':'black-piece';btn.setAttribute('aria-label',TYPES[k].name);btn.onclick=()=>{$('promotionModal').classList.remove('open');pending=null;doMove(m,k)};$('promotionChoices').appendChild(btn)}$('promotionModal').classList.add('open')}
function chooseBuy(k){if(over||phase!=='play'||engineAutoPending||(gameMode==='engine'&&turn==='b'))return;if(purchase===k){purchase=null;render();return}if(points[turn]<TYPES[k].value)return;if(!hasPurchaseSpot(turn,k)){toast(k==='p'?'Pawn limit reached or no legal file available':'Piece limit reached or no legal square available');return}purchase=k;selected=null;legal=[];render()}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1400)}
function render(){
  $('brandIcon').innerHTML=pieceSvg('wn');$('whiteAvatar').innerHTML=pieceSvg('wk');$('blackAvatar').innerHTML=pieceSvg('bk');
  const view=reviewView&&reviewView.position,shownBoard=view?view.board:board,shownTurn=view?view.turn:turn,shownLast=view?view.lastMove:lastMove,marked=reviewView?reviewMarkSquare(reviewView):null;
 const el=$('board');el.innerHTML='';const kpos=inCheck(shownBoard,shownTurn)?kingAt(shownBoard,shownTurn):null;
 for(let r=0;r<4;r++)for(let c=0;c<4;c++){
  const sq=document.createElement('div');sq.className='sq '+((r+c)%2?'dark':'light');
  if(!view&&phase==='setup'&&r===homeRow(setupSide))sq.classList.add('own-half');
  if(!view&&purchase&&ownHalf(turn,r)&&!shownBoard[r][c])sq.classList.add('own-half');
  if(!view&&selected&&selected[0]===r&&selected[1]===c)sq.classList.add('selected');
  if(shownLast&&[shownLast.from,shownLast.to].some(([a,b])=>a===r&&b===c))sq.classList.add('last');
  if(kpos&&kpos[0]===r&&kpos[1]===c)sq.classList.add('checked');
  if(engineHint?.type==='move'){if(engineHint.move.from[0]===r&&engineHint.move.from[1]===c)sq.classList.add('engine-from');if(engineHint.move.to[0]===r&&engineHint.move.to[1]===c)sq.classList.add('engine-to')}
  if(engineHint?.type==='buy'&&engineHint.to[0]===r&&engineHint.to[1]===c)sq.classList.add('engine-to');
  sq.setAttribute('role','gridcell');sq.setAttribute('aria-label',`${nameSq(r,c)}${shownBoard[r][c]?' '+({q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn',k:'king'})[shownBoard[r][c][1]]:''}`);
  const piece=shownBoard[r][c],detail=reviewView&&reviewView.detail,purchasePreview=detail?.type==='buy'&&detail.to[0]===r&&detail.to[1]===c;if(piece){const span=document.createElement('span');span.className='piece piece-'+piece[1]+' '+(sideOf(piece)==='w'?'white-piece':'black-piece');span.innerHTML=pieceSvg(piece);sq.appendChild(span)}else if(purchasePreview){const ghost=document.createElement('span');ghost.className='piece piece-'+detail.piece+' purchase-preview '+(reviewView.side==='w'?'white-piece':'black-piece');ghost.innerHTML=pieceSvg(reviewView.side+detail.piece);sq.appendChild(ghost)}
  if(marked&&marked[0]===r&&marked[1]===c){const badge=document.createElement('span');badge.className='move-rating rating-'+reviewView.grade.toLowerCase();badge.textContent=gradeSymbol(reviewView.grade);badge.title=`${reviewView.grade} · ${reviewView.played}`;badge.setAttribute('aria-label',`${reviewView.grade} rating`);sq.appendChild(badge)}
  const lm=!view&&legal.find(m=>m.to[0]===r&&m.to[1]===c);if(lm){const dot=document.createElement('i');dot.className=lm.capture?'legal-capture':'legal-dot';sq.appendChild(dot)}
  const f=document.createElement('span');f.className='coords coord-file';f.textContent=FILES[c];sq.appendChild(f);const rk=document.createElement('span');rk.className='coords coord-rank';rk.textContent=4-r;sq.appendChild(rk);sq.onclick=()=>clickSquare(r,c);el.appendChild(sq)
 }
 for(const side of ['w','b']){const name=side==='w'?'white':'black',bank=view?view.points:points;$(`${name}Points`).textContent=`${bank[side]} / ${POINT_CAP}`;$(`${name}Card`).classList.toggle('active',view?side===shownTurn:side===turn&&!over);$(`${name}Sub`).textContent=view?(side===shownTurn?'REVIEW · TO MOVE':'REVIEW'):phase==='setup'?(setupSide===side?'PLACE YOUR KING':'WAITING TO PLACE KING'):over?(side===(endReason==='resign'?resignedSide:turn)?(endReason==='resign'?'RESIGNED':'CHECKMATE'):'WINNER'):gameMode==='engine'&&side==='b'?'ENGINE · BLACK':(side===turn?'YOUR TURN':'WAITING')}
 const status=$('status'),icon=$('statusIcon'),text=$('statusText'),check=inCheck(shownBoard,shownTurn);status.className='status'+(check?' checking':'')+(over&&!view?' over':'');
  if(view){icon.innerHTML=pieceSvg(reviewView.side+'k');text.innerHTML=`<strong>Reviewing ${reviewView.side==='w'?'White':'Black'}’s ${esc(reviewView.played)}.</strong> Best action: ${esc(reviewView.bestText)}.`;$('boardHint').textContent=`Review · ${reviewView.played}`}
 else if(phase==='setup'){icon.innerHTML=pieceSvg(setupSide+'k');text.innerHTML=`<strong>${setupSide==='w'?'White':'Black'}, place your king.</strong> Choose any highlighted square on your back rank.`;$('boardHint').textContent=`Place ${setupSide==='w'?'White':'Black'} king on the back rank`}
 else if(over){icon.innerHTML=pieceSvg((endReason==='resign'?(resignedSide==='w'?'b':'w'):turn)+'k');text.innerHTML=`<strong>${endReason==='resign'?(resignedSide==='w'?'White resigned.':'Black resigned.'):'Checkmate.'}</strong> ${endReason==='resign'?(resignedSide==='w'?'Black':'White'):(turn==='w'?'Black':'White')} wins!`;$('boardHint').textContent='Game over · start a new game'}
 else if(gameMode==='engine'&&turn==='b'){icon.innerHTML=pieceSvg('bk');text.innerHTML=`<strong>Black engine is thinking${check?' · in check':''}.</strong> It will play its top-rated legal action.`;$('boardHint').textContent='Black engine to act'}
 else if(check){icon.textContent='!';text.innerHTML=`<strong>${turn==='w'?'White':'Black'} is in check.</strong> Move to safety or buy a piece that blocks the attack.`;$('boardHint').textContent='In check · king may move'}
 else{icon.innerHTML=pieceSvg(turn+'p');text.innerHTML=`<strong>${turn==='w'?'White':'Black'} to act.</strong> Move, buy a piece, or skip to earn up to 2 points (12 point bank cap).`;$('boardHint').textContent=purchase?`Choose a square in ${turn==='w'?'White':'Black'}’s half`:'Green outline marks your half'}
 $('actionCount').textContent=`${actions.length} ${actions.length===1?'ACTION':'ACTIONS'}`;const hist=$('historyList');if(!actions.length)hist.innerHTML='<div class="empty">Your game will unfold here.</div>';else{hist.innerHTML='';actions.forEach((a,i)=>{const row=document.createElement('div');row.className='action-row';row.innerHTML=`<span class="action-num">${i+1}.</span><span class="action-text"><b>${a.side==='w'?'W':'B'}</b> &nbsp;${esc(a.text)}</span><span class="action-points">${a.detail?.type==='skip'?`+${a.delta}`:`${a.delta>0?'+':''}${a.delta||''}`}</span>`;hist.appendChild(row)});hist.scrollTop=hist.scrollHeight}
 const engineTurn=gameMode==='engine'&&turn==='b';$('skip').disabled=phase!=='play'||over||check||engineTurn||engineAutoPending;$('skipActions').style.display=phase==='play'&&!over?'grid':'none';$('shop').style.display=phase==='play'&&!over?'grid':'none';$('undo').disabled=!history.length;$('engineButton').style.display=phase==='play'&&!over&&!engineTurn?'':'none';$('engineButton').disabled=reviewBusy||engineAutoPending;$('modeToggle').textContent=gameMode==='engine'?'vs Engine':'2 Player';$('modeToggle').setAttribute('aria-pressed',gameMode==='engine'?'true':'false');$('modeToggle').classList.toggle('primary',gameMode==='engine');$('modeToggle').title=gameMode==='engine'?'Switch to two-player mode':'Play as White against the engine as Black';$('reviewButton').style.display=over&&actions.length?'':'none';$('resign').style.display=over?'':'none';$('resign').disabled=phase!=='play'||over;$('resign').title=phase==='play'?'Resign the current game':'Place both kings to begin a game';$('turnActions').style.display='grid';$('shop').innerHTML='';for(const k of ['q','r','b','n','p']){const item=document.createElement('button');item.className='buy'+(!hasPurchaseSpot(turn,k)?' unaffordable':'')+(purchase===k?' chosen':'');item.disabled=engineTurn||engineAutoPending;item.innerHTML=`<span class="buy-figure ${turn==='w'?'white-piece':'black-piece'}">${pieceSvg(turn+k)}</span><span class="buy-price">${TYPES[k].value} pt${TYPES[k].value>1?'s':''}</span>`;item.title=`Buy ${TYPES[k].name} · ${TYPES[k].value} point${TYPES[k].value>1?'s':''}`;item.onclick=()=>chooseBuy(k);$('shop').appendChild(item)}$('turnHint').textContent=phase==='setup'?'Players place kings in turn; no points are spent.':gameMode==='engine'?'You are White against the engine as Black. The engine chooses moves, buys, or skips.':check?'A king may move only while in check. You may buy only a piece that gets you out of check.':'One action per turn · Bank cap 12 · King moves only while in check.';if(reviewResults)renderReviewRows()
}function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
$('skip').onclick=doSkip;$('resign').onclick=resign;$('modeToggle').onclick=toggleGameMode;$('undo').onclick=undo;$('engineButton').onclick=runEngine;$('reviewButton').onclick=startReview;$('newGame').onclick=()=>{if(actions.length&&!over&&!confirm('Start a new game? The current game will be lost.'))return;reset()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(pending){pending=null;$('promotionModal').classList.remove('open')}else if(purchase){purchase=null;render()}}});reset();
})();
